/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.presentation;

import co.unicauca.microkernel.infra.Publisher;
import co.unicauca.microkernel.business.DeliveryService;
import co.unicauca.microkernel.business.ProductService;
import co.unicauca.microkernel.common.entities.Delivery;
import co.unicauca.microkernel.common.entities.Product;
import com.google.gson.Gson;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ahurtado
 */
public class GUISendProduct extends javax.swing.JFrame{
    
    private final ProductService productService;
    private DeliveryService deliveryService;
    List<Product> products;
    Publisher publisher;

    /**
     * Creates new form GUISendProduct
     */
    public GUISendProduct() {
        initComponents();
        productService = new ProductService();
        publisher = new Publisher();
        products = productService.getAll();
        for (int index = 0; index < products.size(); index++) {
        ProductoSeleccion.addItem(products.get(index).getName());
        }
        EnvioCajaTexto.setEnabled(false);
        EnvioCajaTexto.setText("...");
        GuardarBoton.setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloTexto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ProductoTexto = new javax.swing.JLabel();
        ProductoSeleccion = new javax.swing.JComboBox<>();
        DistanciaTexto = new javax.swing.JLabel();
        DistanciaCajaTexto = new javax.swing.JTextField();
        CodigoPaisTexto = new javax.swing.JLabel();
        CodigoPaisCajaTexto = new javax.swing.JTextField();
        EnvioTexto = new javax.swing.JLabel();
        EnvioCajaTexto = new javax.swing.JTextField();
        GuardarTexto = new javax.swing.JLabel();
        GuardarLista = new javax.swing.JComboBox<>();
        DireccionTexto = new javax.swing.JLabel();
        CiudadTexto = new javax.swing.JLabel();
        DireccionCajaTexto = new javax.swing.JTextField();
        CiudadCajaTexto = new javax.swing.JTextField();
        GuardarBoton = new javax.swing.JButton();
        CalcularBoton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloTexto.setText("Gestión del producto");
        getContentPane().add(TituloTexto, java.awt.BorderLayout.PAGE_START);

        ProductoTexto.setText("Seleccione el producto");

        ProductoSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoSeleccionActionPerformed(evt);
            }
        });

        DistanciaTexto.setText("Indique la distancia en Km");

        DistanciaCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanciaCajaTextoActionPerformed(evt);
            }
        });

        CodigoPaisTexto.setText("Indique el código del país");

        CodigoPaisCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoPaisCajaTextoActionPerformed(evt);
            }
        });

        EnvioTexto.setText("Costo del Envío");

        EnvioCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvioCajaTextoActionPerformed(evt);
            }
        });

        GuardarTexto.setText("Seleccione el lugar a Guardar");

        GuardarLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventas", "Inventario de salida", "Despachos"}));
        GuardarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarListaActionPerformed(evt);
            }
        });

        DireccionTexto.setText("Dirección");

        CiudadTexto.setText("Ciudad");

        DireccionCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionCajaTextoActionPerformed(evt);
            }
        });

        CiudadCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadCajaTextoActionPerformed(evt);
            }
        });

        GuardarBoton.setText("Guardar");
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });

        CalcularBoton.setText("Calcular Valor de Envío");
        CalcularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DistanciaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(ProductoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CodigoPaisTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addComponent(DireccionTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addComponent(CiudadTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnvioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(GuardarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GuardarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(310, 310, 310))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(GuardarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(CalcularBoton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CiudadCajaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                                .addComponent(ProductoSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DireccionCajaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CodigoPaisCajaTexto))
                                .addComponent(DistanciaCajaTexto)
                                .addComponent(EnvioCajaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DistanciaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(DistanciaCajaTexto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoPaisCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoPaisTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DireccionCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CiudadTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CiudadCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnvioCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnvioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcularBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarBoton)))
        );

        CodigoPaisTexto.getAccessibleContext().setAccessibleName("Country Code");
        GuardarTexto.getAccessibleContext().setAccessibleName("Save ");
        GuardarLista.getAccessibleContext().setAccessibleName("Type List");
        DireccionTexto.getAccessibleContext().setAccessibleName("Adress");
        CiudadTexto.getAccessibleContext().setAccessibleName("City");
        CalcularBoton.getAccessibleContext().setAccessibleName("Calculate Value");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularBotonActionPerformed
        // TODO add your handling code here:
        Delivery deliveryEntity = GetDeliveryEntity(); 
        try {
            EnvioCajaTexto.setText("" + deliveryEntity.getCosto());
            CalcularBoton.setVisible(true);
        } catch (Exception exception) {
            System.out.println("No se puede calcular el costo del envío. Debido a: " + exception.getMessage());
        }
        
    }//GEN-LAST:event_CalcularBotonActionPerformed

    private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
        // TODO add your handling code here:
        Delivery deliveryEntity = GetDeliveryEntity(); 
        String[] listaEventos = {"SoldProducts", "Inventory", "ProductstoDelivery"}; 
        String queque = listaEventos[this.GuardarLista.getSelectedIndex()]; 
        Gson gson = new Gson();
        GuardarBoton.setVisible(true);
        String msgJson = gson.toJson(deliveryEntity);
        publisher.publish(msgJson, queque);
    }//GEN-LAST:event_GuardarBotonActionPerformed

    
    
    private void DistanciaCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciaCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaCajaTextoActionPerformed

    private void ProductoSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoSeleccionActionPerformed

    private void GuardarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarListaActionPerformed

    private void EnvioCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvioCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnvioCajaTextoActionPerformed

    private void CodigoPaisCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoPaisCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoPaisCajaTextoActionPerformed

    private void DireccionCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionCajaTextoActionPerformed

    private void CiudadCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiudadCajaTextoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularBoton;
    private javax.swing.JTextField CiudadCajaTexto;
    private javax.swing.JLabel CiudadTexto;
    private javax.swing.JTextField CodigoPaisCajaTexto;
    private javax.swing.JLabel CodigoPaisTexto;
    private javax.swing.JTextField DireccionCajaTexto;
    private javax.swing.JLabel DireccionTexto;
    private javax.swing.JTextField DistanciaCajaTexto;
    private javax.swing.JLabel DistanciaTexto;
    private javax.swing.JTextField EnvioCajaTexto;
    private javax.swing.JLabel EnvioTexto;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JComboBox<String> GuardarLista;
    private javax.swing.JLabel GuardarTexto;
    private javax.swing.JComboBox<String> ProductoSeleccion;
    private javax.swing.JLabel ProductoTexto;
    private javax.swing.JLabel TituloTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
    private Delivery GetDeliveryEntity(){
        try {
            deliveryService = new DeliveryService();
            Product productoSeleccionado = products.get(this.ProductoSeleccion.getSelectedIndex());
            Delivery delivery = new Delivery(productoSeleccionado,
                    Double.parseDouble(DistanciaCajaTexto.getText()),
                    CodigoPaisCajaTexto.getText(),
                    CiudadCajaTexto.getText(),
                    DireccionCajaTexto.getText());
            double cost = deliveryService.calculateDeliveryCost(delivery);
            delivery.setCosto(cost);
            return delivery;
        } catch (Exception ex) {
            Logger.getLogger(GUISendProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null; 
    }
}
